### ISSUE TITLE
Matching seems broken

### ISSUE THREAD

**Issue by tivac** [shardulm94/vscode-trailingspaces#1]
Just installed this into `vscode@0.10.10` and I'm unable to get live OR manual matching to work.

Settings:
```json
"trailing-spaces.logLevel": "error",
"trailing-spaces.includeEmptyLines": false,
"trailing-spaces.includeCurrentLine": false,
"trailing-spaces.regexp": "[ \t]+",
"trailing-spaces.liveMatching": true,
"trailing-spaces.modifiedLinesOnly": false,
"trailing-spaces.syntaxIgnore": [],
"trailing-spaces.trimOnSave": true
```

but even after a restart of VSCode opening a file like this shows nothing:

```js
asdfa   

d    

ddddd

```

If I attempt to manually trigger matching I get this:

`Running the contributed command:'trailing-spaces.highlightTrailingSpaces' failed.`

I'm getting a relevant-seeming error in the debugging console:

```
Invalid regular expression: /(?<=S)[ 	]+$$/: Invalid group: SyntaxError: Invalid regular expression: /(?<=S)[ 	]+$$/: Invalid group
    at new RegExp (native)
    at TrailingSpaces.findTrailingSpaces (C:\Users\pcavit\.vscode\extensions\shardulm94.trailing-spaces-0.1.2\out\src\trailing-spaces\trailing-spaces.js:138:36)
    at TrailingSpaces.matchTralingSpaces (C:\Users\pcavit\.vscode\extensions\shardulm94.trailing-spaces-0.1.2\out\src\trailing-spaces\trailing-spaces.js:103:28)
    at C:\Users\pcavit\.vscode\extensions\shardulm94.trailing-spaces-0.1.2\out\src\trailing-spaces\trailing-spaces.js:31:23
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:7:15735)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:7:17188)
    at e._acceptSelectionsChanged (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:18:7323)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:14:15281)
    at c (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:12:7591)
    at h (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:12:8251)
    at doNTCallback0 (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

**Comment by shardulm94** [comment]
I have published a new version of the extension (v0.2.0) to the marketplace. Could you please update and confirm if this is fixed?
