### ISSUE TITLE
Crashes extension host all the time since last VSCode update

### ISSUE THREAD

**Issue by banks** [shardulm94/vscode-trailingspaces#19]
Hi,

First off, this may not be an issue with this extension at all but it seems most likely based on what I can see.

I've used this extension for ages (at least a year) with no issues. Until this week I have never has any issues.

Since the latest VSCode update this week (to Version 1.26.0), I get errors the "Extension host terminated unexpectedly" very often (every few minutes) and I have to restart it or reload VSCode to get any extensions to work again.

When i look in the Developer Tools logs, the only errors I see are all realted to this extension.

But interestingly, disabling this extension and reloading _doesn't_ seem to fix the issue. At first I assumed these errors must just be a red herring and not that cause of the extension host crashes. That could still be true, but I see no other errors in the console at all in that case. I've not yet tried removing the extension entirely.

There are a couple of different error traces:

```
ERR Cannot read property 'split' of undefined: TypeError: Cannot read property 'split' of undefined
    at Diff.lineDiff.tokenize (/Users/banks/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/node_modules/diff/src/diff/line.js:7:32)
    at Diff.diff (/Users/banks/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/node_modules/diff/src/diff/base.js:27:39)
    at Object.diffLines (/Users/banks/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/node_modules/diff/src/diff/line.js:31:71)
    at TrailingSpaces.modifiedLinesAsNumbers (/Users/banks/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/out/src/trailing-spaces/trailing-spaces.js:248:28)
    at TrailingSpaces.getModifiedLineNumbers (/Users/banks/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/out/src/trailing-spaces/trailing-spaces.js:261:21)
    at TrailingSpaces.findRegionsToDelete (/Users/banks/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/out/src/trailing-spaces/trailing-spaces.js:277:38)
    at TrailingSpaces.deleteTrailingRegions (/Users/banks/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/out/src/trailing-spaces/trailing-spaces.js:205:32)
    at TrailingSpaces.deleteTrailingSpacesCore (/Users/banks/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/out/src/trailing-spaces/trailing-spaces.js:134:14)
    at TrailingSpaces.deleteTrailingSpaces (/Users/banks/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/out/src/trailing-spaces/trailing-spaces.js:114:14)
    at /Users/banks/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/out/src/trailing-spaces/trailing-spaces.js:86:35
    at e.edit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:766:630)
    at /Users/banks/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/out/src/trailing-spaces/trailing-spaces.js:85:32
    at Array.forEach (<anonymous>)
    at /Users/banks/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/out/src/trailing-spaces/trailing-spaces.js:82:46
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:218)
    at e.$acceptModelSaved (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:728:141)
    at e._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:983)
    at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:701)
    at e._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:670:767)
    at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:670:536)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:669:452
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:672:575
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:96:903
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:218)
    at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:162:713)
    at Socket._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:162:932)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

And 

```
ERR ENOENT: no such file or directory, open 'extension-output-#2': Error: ENOENT: no such file or directory, open 'extension-output-#2'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:172:20)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:510:29)
    at TrailingSpaces.freezeLastVersion (/Users/banks/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/out/src/trailing-spaces/trailing-spaces.js:266:51)
    at /Users/banks/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/out/src/trailing-spaces/trailing-spaces.js:56:19
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:218)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:773:112
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:218)
    at e.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:771:330)
    at e._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:983)
    at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:671:701)
    at e._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:670:767)
    at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:670:536)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:669:452
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:672:575
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:96:903
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:98:218)
    at a (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:162:713)
    at Socket._socketDataListener (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:162:932)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

Both seem to be in this extension from the file names.

If I can provide any more details or try anything to help narrow down the cause I'm very willing to help!

Thanks.

VSCode Version 1.26.0 (1.26.0)
macOS High Sierra 10.13.6 (17G65)
Trailing Spaces 0.2.11

**Comment by banks** [comment]
Hmm I uninstalled completely and still see extension host crashes now with no errors in log.

So I don't think these errors are responsible for that crash but they may be useful/worth fixing anyway? If not feel free to close.

**Comment by Duracell1989** [comment]
I've had the same issue after upgrading VSCode from 1.26.1 to 1.27.1
Just like @banks; disabling the extensions didn't fix the problem.
But; [cleaning/deleting the workspace](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#clean-the-workspace-directory) did the trick for me.

**Comment by fuminchao** [comment]
same error when executing "Delete Modified lines only"
I have tried cleaning the workspace completely
```
[2019-02-21 13:49:51.322] [exthost] [error] TypeError: Cannot read property 'split' of undefined
	at Diff.lineDiff.tokenize (/Users/mincfu/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/node_modules/diff/lib/diff/line.js:22:32)
	at Diff.diff (/Users/mincfu/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/node_modules/diff/lib/diff/base.js:35:39)
	at Object.diffLines (/Users/mincfu/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/node_modules/diff/lib/diff/line.js:47:19)
	at TrailingSpaces.modifiedLinesAsNumbers (/Users/mincfu/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/out/src/trailing-spaces/trailing-spaces.js:248:28)
	at TrailingSpaces.getModifiedLineNumbers (/Users/mincfu/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/out/src/trailing-spaces/trailing-spaces.js:261:21)
	at TrailingSpaces.findRegionsToDelete (/Users/mincfu/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/out/src/trailing-spaces/trailing-spaces.js:277:38)
	at TrailingSpaces.deleteTrailingRegions (/Users/mincfu/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/out/src/trailing-spaces/trailing-spaces.js:205:32)
	at TrailingSpaces.deleteTrailingSpacesCore (/Users/mincfu/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/out/src/trailing-spaces/trailing-spaces.js:134:14)
	at TrailingSpaces.deleteTrailingSpacesModifiedLinesOnly (/Users/mincfu/.vscode/extensions/shardulm94.trailing-spaces-0.2.11/out/src/trailing-spaces/trailing-spaces.js:119:14)
	at /private/var/folders/dw/g0p5vsc14dsctcq48yqjjsrh39cpv6/T/AppTranslocation/86D79B7F-5266-4DF6-B38B-4492523A189F/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:733:792
```

**Comment by shardulm94** [comment]
@fuminchao Can you try to see if the new beta release has the same issue? The stacktrace indicates an error in the diff library being used in this extension. I upgraded the library version in the beta release.
https://github.com/shardulm94/vscode-trailingspaces/releases/tag/v0.3.0-rc1
https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by fuminchao** [comment]
@shardulm94 
The error was gone on 0.3.0-rc1 👍

**Comment by shardulm94** [comment]
@fuminchao Thanks for verifying! Will be officially release this weekend.
