### ISSUE TITLE
ENOENT: no such file or directory, open 'rendererLog'

### ISSUE THREAD

**Issue by pzelnip** [shardulm94/vscode-trailingspaces#22]
This is reported to be an error from this extension according to https://github.com/Microsoft/vscode/issues/58346

Having now uninstalled the trailing spaces extension I haven't seen the error recur for me, which is consistent with the hypothesis that it's related to this extension.

**Comment by crystalfp** [comment]
In the log you find:
```
[2018-12-16 06:58:26.479] [renderer1] [error] ENOENT: no such file or directory, open 'C:\Program Files\Microsoft VS Code\rendererLog': Error: ENOENT: no such file or directory, open 'C:\Program Files\Microsoft VS Code\rendererLog'
	at Object.fs.openSync (fs.js:646:18)
	at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
	at Object.fs.readFileSync (fs.js:551:33)
	at Object.exports.wrapFsWithAsar.fs.readFileSync (ELECTRON_ASAR.js:538:29)
	at TrailingSpaces.freezeLastVersion (C:\Users\Mario Valle\.vscode\extensions\shardulm94.trailing-spaces-0.2.11\out\src\trailing-spaces\trailing-spaces.js:266:51)
	at C:\Users\Mario Valle\.vscode\extensions\shardulm94.trailing-spaces-0.2.11\out\src\trailing-spaces\trailing-spaces.js:56:19
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:133:218)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:634:804
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:133:218)
	at e.$acceptDocumentsAndEditorsDelta (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:541:823)
	at t._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:837)
	at t._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:509)
	at t._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:126)
	at t._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:59)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:653:895
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:130:793
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:133:218)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:186:147)
	at Socket.n._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:186:368)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```
Indeed it seems the error has no visible consequences. Only annoying.

**Comment by shardulm94** [comment]
Found the root cause here. VSCode also considers output windows as text editors according to Microsoft/vscode#36579. The extension was trying to read the path provided for these editors, but these paths are not file paths. They are probably in memory, hence `No such file or directory`. The extension now only tries to read the file if the scheme is `file`. This should fix the issue. 
You can test this out with the latest beta release.
https://github.com/shardulm94/vscode-trailingspaces/releases/tag/v0.3.0-rc3
https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by crystalfp** [comment]
RC3 works! Thanks for your investigative work.

**Comment by shardulm94** [comment]
@crystalfp Thanks for verifying! Should be officially released this weekend.
